name: Linter Go
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      #melakukan checkout kode pada branch master yang baru saja di-push
      - name: Checkout code
        uses: actions/checkout@v2

      #melakukan setup Go pada versi 1.19.5 pada environment yang akan digunakan untuk menjalankan Linter
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.5'

      #meng-install Linter Module pada proyek Go menggunakan command go get
      - name: Install Linter Module
        run: go get golang.org/x/lint/golint

      #meng-install Linter Go menggunakan command go install
      - name: Install Linter
        run: go install golang.org/x/lint/golint

      #menjalankan Linter Go pada seluruh file kode yang ada pada proyek Go menggunakan command golint ./...
      - name: Run Linter
        run: golint ./...

      #mengupload hasil linting pada proyek Go ke dalam file results.txt menggunakan Github Actions
      - name: Upload Linter Results
        uses: actions/upload-artifact@v2
        with:
          name: Lint Results
          path: results.txt